name: Security vulnerabilities check
on: push

jobs:
  software-composition-analysis-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code on the runner
        uses: actions/checkout@v4
      - name: Software Composition Analysis using Snyk
        uses: snyk/actions/node@master
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
  static-app-security-testing-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=javaprojectkey -Dsonar.organization=javaorgkey -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

